version: '3.8'

services:
  db:
    image: postgres:latest
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  nestjs:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env

volumes:
  db-data:
