version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: enira94
      POSTGRES_DB: register_database
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  nestjs:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgres://postgres:enira94@db:5432/register_database

volumes:
  db-data: